In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])

In [5]:
print(a *2)

[2 4 6 8]


In [6]:
[1,2,3,4] * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
print(a +4)

[5 6 7 8]


In [8]:
print(a+a)

[2 4 6 8]


In [10]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

In [11]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [14]:
print(matrix[0,0])
print(matrix[1,0])

1
4


In [15]:
print(matrix[:,0])

[1 4]
